//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsapm.PluginInstaller.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wsapm_PluginInstaller {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wsapm_PluginInstaller() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wsapm.PluginInstaller.Resources.Wsapm.PluginInstaller", typeof(Wsapm_PluginInstaller).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to start Windows Server Advanced Power Management....
        /// </summary>
        internal static string PluginInstaller_AnyKeyWsapmStart {
            get {
                return ResourceManager.GetString("PluginInstaller_AnyKeyWsapmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of arguments..
        /// </summary>
        internal static string PluginInstaller_ArgsError {
            get {
                return ResourceManager.GetString("PluginInstaller_ArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string PluginInstaller_GeneralError {
            get {
                return ResourceManager.GetString("PluginInstaller_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install plugin....
        /// </summary>
        internal static string PluginInstaller_InstallingPlugin {
            get {
                return ResourceManager.GetString("PluginInstaller_InstallingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Windows Server Advanced Power Management service....
        /// </summary>
        internal static string PluginInstaller_StartingService {
            get {
                return ResourceManager.GetString("PluginInstaller_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Windows Server Advanced Power Management service....
        /// </summary>
        internal static string PluginInstaller_StoppingService {
            get {
                return ResourceManager.GetString("PluginInstaller_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall plugin....
        /// </summary>
        internal static string PluginInstaller_UninstallingPlugin {
            get {
                return ResourceManager.GetString("PluginInstaller_UninstallingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing plugin settings....
        /// </summary>
        internal static string PluginInstaller_UninstallingPluginSettings {
            get {
                return ResourceManager.GetString("PluginInstaller_UninstallingPluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Wsapm.exe to shutdown....
        /// </summary>
        internal static string PluginInstaller_WaitingForWsapmToShutdown {
            get {
                return ResourceManager.GetString("PluginInstaller_WaitingForWsapmToShutdown", resourceCulture);
            }
        }
    }
}
