//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsapm.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wsapm_Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wsapm_Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wsapm.Core.Resources.Wsapm.Core", typeof(Wsapm_Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one policy satisfied.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionModeAtLeastOnePolicySatisfied {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionModeAtLeastOnePolicySatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policy satisfied.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionModeNoPolicySatisfied {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionModeNoPolicySatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hibernate.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionNameHibernate {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionNameHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shut down.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionNameShutdown {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionNameShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standby.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionNameStandby {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionNameStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start program.
        /// </summary>
        internal static string ActionAfterPolicyCheck_ActionNameStartProgram {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheck_ActionNameStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute user defined action after policy check ({0}).
        /// </summary>
        internal static string ActionAfterPolicyCheckManager_ExecutingAction {
            get {
                return ResourceManager.GetString("ActionAfterPolicyCheckManager_ExecutingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CPU load cannot be retrieved (maybe the performance counters are broken).
        /// </summary>
        internal static string CpuLoadAverage_RetrieveLoadError {
            get {
                return ResourceManager.GetString("CpuLoadAverage_RetrieveLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU load greater than {0}% ({1}%).
        /// </summary>
        internal static string CpuLoadCheck_CpuLoadCheckReason {
            get {
                return ResourceManager.GetString("CpuLoadCheck_CpuLoadCheckReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical volume load [{0}] greater than {1} KB/s ({2} KB/s).
        /// </summary>
        internal static string HddLoadCheck_HddLoadReason {
            get {
                return ResourceManager.GetString("HddLoadCheck_HddLoadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical volume &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string HddLoadCheck_HddNotAvailable {
            get {
                return ResourceManager.GetString("HddLoadCheck_HddNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HDD load cannot be retrieved (maybe the performance counters are broken).
        /// </summary>
        internal static string HddLoadSingleVolumeAverage_RetrieveLoadError {
            get {
                return ResourceManager.GetString("HddLoadSingleVolumeAverage_RetrieveLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical volume &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string HddLoadSingleVolumeBase_LogicalVolumeCannotBeFound {
            get {
                return ResourceManager.GetString("HddLoadSingleVolumeBase_LogicalVolumeCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The memory load cannot be retrieved.
        /// </summary>
        internal static string MemoryLoadAverage_RetrieveLoadError {
            get {
                return ResourceManager.GetString("MemoryLoadAverage_RetrieveLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory load greater than {0}% ({1}%).
        /// </summary>
        internal static string MemoryLoadCheck_MemoryLoadCheckReason {
            get {
                return ResourceManager.GetString("MemoryLoadCheck_MemoryLoadCheckReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network load (upload + download) [{0}] greater than {1} KBit/s ({2} KBit/s).
        /// </summary>
        internal static string NetworkLoadCheck_CombinedNetworkLoadReason {
            get {
                return ResourceManager.GetString("NetworkLoadCheck_CombinedNetworkLoadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network load (download) [{0}] greater than {1} KBit/s ({2} KBit/s).
        /// </summary>
        internal static string NetworkLoadCheck_DownloadNetworkLoadReason {
            get {
                return ResourceManager.GetString("NetworkLoadCheck_DownloadNetworkLoadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network interface &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string NetworkLoadCheck_NicNotAvailable {
            get {
                return ResourceManager.GetString("NetworkLoadCheck_NicNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network load (upload) [{0}] greater than {1} KBit/s ({2} KBit/s).
        /// </summary>
        internal static string NetworkLoadCheck_UploadNetworkLoadReason {
            get {
                return ResourceManager.GetString("NetworkLoadCheck_UploadNetworkLoadReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network load cannot be retrieved (maybe the performance counters are broken).
        /// </summary>
        internal static string NetworkLoadSingleNicAverage_RetrieveLoadError {
            get {
                return ResourceManager.GetString("NetworkLoadSingleNicAverage_RetrieveLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting network connections.
        /// </summary>
        internal static string NetworkManager_ResetNetworkConnections {
            get {
                return ResourceManager.GetString("NetworkManager_ResetNetworkConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection &apos;{0}&apos; reset.
        /// </summary>
        internal static string NetworkManager_ResetNetworkInterface {
            get {
                return ResourceManager.GetString("NetworkManager_ResetNetworkInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset networ connection &apos;{0}&apos;.
        /// </summary>
        internal static string NetworkManager_ResetNetworkInterfaceFailed {
            get {
                return ResourceManager.GetString("NetworkManager_ResetNetworkInterfaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset network connections.
        /// </summary>
        internal static string NetworkManager_ResetNetworkInterfaceGeneralError {
            get {
                return ResourceManager.GetString("NetworkManager_ResetNetworkInterfaceGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network access to &apos;{0}&apos;.
        /// </summary>
        internal static string NetworkResourcesCheck_NetworkResourcesCheckReason {
            get {
                return ResourceManager.GetString("NetworkResourcesCheck_NetworkResourcesCheckReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine {0} online.
        /// </summary>
        internal static string PingCheck_MachineOnlineReason {
            get {
                return ResourceManager.GetString("PingCheck_MachineOnlineReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading plugins.
        /// </summary>
        internal static string PluginManager_ErrorLoadingPlugins {
            get {
                return ResourceManager.GetString("PluginManager_ErrorLoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking policy of plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_ErrorPluginCheckPolicy {
            get {
                return ResourceManager.GetString("PluginManager_ErrorPluginCheckPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while initializing plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_ErrorPluginInitialize {
            get {
                return ResourceManager.GetString("PluginManager_ErrorPluginInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while preparation of plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_ErrorPluginPrepare {
            get {
                return ResourceManager.GetString("PluginManager_ErrorPluginPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while tearing down plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_ErrorPluginTearDown {
            get {
                return ResourceManager.GetString("PluginManager_ErrorPluginTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking policy of plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_PluginCheckPolicy {
            get {
                return ResourceManager.GetString("PluginManager_PluginCheckPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_PluginInitialized {
            get {
                return ResourceManager.GetString("PluginManager_PluginInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginManager_PluginPrepared {
            get {
                return ResourceManager.GetString("PluginManager_PluginPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; teared down.
        /// </summary>
        internal static string PluginManager_PluginTearedDown {
            get {
                return ResourceManager.GetString("PluginManager_PluginTearedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest.
        /// </summary>
        internal static string PluginManifestReader_InvalidManifestError {
            get {
                return ResourceManager.GetString("PluginManifestReader_InvalidManifestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process {0} found.
        /// </summary>
        internal static string ProcessCheck_ProcessFoundReason {
            get {
                return ResourceManager.GetString("ProcessCheck_ProcessFoundReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting program &apos;{0}&apos;.
        /// </summary>
        internal static string ProgramManager_FailedStartProgram {
            get {
                return ResourceManager.GetString("ProgramManager_FailedStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting program &apos;{0}&apos;.
        /// </summary>
        internal static string ProgramManager_StartProgram {
            get {
                return ResourceManager.GetString("ProgramManager_StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading a plugin.
        /// </summary>
        internal static string PuginLoader_CompositionError {
            get {
                return ResourceManager.GetString("PuginLoader_CompositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load manifest for plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PuginLoader_ManifestMissingError {
            get {
                return ResourceManager.GetString("PuginLoader_ManifestMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled uptime until {0}.
        /// </summary>
        internal static string ScheduledUptimeCheck_UptimeDefinedReason {
            get {
                return ResourceManager.GetString("ScheduledUptimeCheck_UptimeDefinedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting service &apos;{0}&apos;.
        /// </summary>
        internal static string ServiceManager_RestartService {
            get {
                return ResourceManager.GetString("ServiceManager_RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart service &apos;{0}&apos;.
        /// </summary>
        internal static string ServiceManager_RestartServiceFailed {
            get {
                return ResourceManager.GetString("ServiceManager_RestartServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be deleted.
        /// </summary>
        internal static string SettingsManager_DeleteSettingsError {
            get {
                return ResourceManager.GetString("SettingsManager_DeleteSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid settings file..
        /// </summary>
        internal static string SettingsManager_ImportSettingsError {
            get {
                return ResourceManager.GetString("SettingsManager_ImportSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading settings.
        /// </summary>
        internal static string SettingsManager_LoadSettingsError {
            get {
                return ResourceManager.GetString("SettingsManager_LoadSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving settings.
        /// </summary>
        internal static string SettingsManager_SaveSettingsError {
            get {
                return ResourceManager.GetString("SettingsManager_SaveSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Computer enters hibernate mode [Remote].
        /// </summary>
        internal static string ShutdownManager_Hibernate {
            get {
                return ResourceManager.GetString("ShutdownManager_Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Computer is restarted [Remote].
        /// </summary>
        internal static string ShutdownManager_Restart {
            get {
                return ResourceManager.GetString("ShutdownManager_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Computer is shut down [Remote].
        /// </summary>
        internal static string ShutdownManager_Shutdown {
            get {
                return ResourceManager.GetString("ShutdownManager_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Computer enters standby mode [Remote].
        /// </summary>
        internal static string ShutdownManager_Standby {
            get {
                return ResourceManager.GetString("ShutdownManager_Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote shut down: Waiting for remote shut down commands on UDP port {0}.
        /// </summary>
        internal static string ShutdownManager_StartListening {
            get {
                return ResourceManager.GetString("ShutdownManager_StartListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote shut down: Stopped waiting for remote shut down commands on UDP port {0}.
        /// </summary>
        internal static string ShutdownManager_StopListening {
            get {
                return ResourceManager.GetString("ShutdownManager_StopListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received remote shut down command, but with wrong password.
        /// </summary>
        internal static string ShutdownManager_WarningWrongPassword {
            get {
                return ResourceManager.GetString("ShutdownManager_WarningWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create power request.
        /// </summary>
        internal static string StandbyManager_CreatePowerRequestFail {
            get {
                return ResourceManager.GetString("StandbyManager_CreatePowerRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power availability requests not supported by operation system.
        /// </summary>
        internal static string StandbyManager_PowerAvailabilityRequestsNotSupported {
            get {
                return ResourceManager.GetString("StandbyManager_PowerAvailabilityRequestsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power availability requests supported by operation system.
        /// </summary>
        internal static string StandbyManager_PowerAvailabilityRequestsSupported {
            get {
                return ResourceManager.GetString("StandbyManager_PowerAvailabilityRequestsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Windows idle timer.
        /// </summary>
        internal static string StandbyManager_ResetWindowsIdleTimer {
            get {
                return ResourceManager.GetString("StandbyManager_ResetWindowsIdleTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset Windows idle timer.
        /// </summary>
        internal static string StandbyManager_ResetWindowsIdleTimerFailed {
            get {
                return ResourceManager.GetString("StandbyManager_ResetWindowsIdleTimerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby suspension deactivated.
        /// </summary>
        internal static string StandbyManager_StandbyEnabled {
            get {
                return ResourceManager.GetString("StandbyManager_StandbyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deactivate standby suspension.
        /// </summary>
        internal static string StandbyManager_StandbyEnableFailed {
            get {
                return ResourceManager.GetString("StandbyManager_StandbyEnableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server Advanced Power Management: Standby suspended.
        /// </summary>
        internal static string StandbyManager_StandbySuspended {
            get {
                return ResourceManager.GetString("StandbyManager_StandbySuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby unterdrückt.
        /// </summary>
        internal static string StandbyManager_StandbySuspendedWithoutReason {
            get {
                return ResourceManager.GetString("StandbyManager_StandbySuspendedWithoutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby suspended (Reason: {0}).
        /// </summary>
        internal static string StandbyManager_StandbySuspendedWithReason {
            get {
                return ResourceManager.GetString("StandbyManager_StandbySuspendedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to suspend standby mode.
        /// </summary>
        internal static string StandbyManager_SuspendStandbyFailed {
            get {
                return ResourceManager.GetString("StandbyManager_SuspendStandbyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uptime until {0}.
        /// </summary>
        internal static string TemporaryUptimeCheck_UptimeDefinedReason {
            get {
                return ResourceManager.GetString("TemporaryUptimeCheck_UptimeDefinedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uptime could not be deleted.
        /// </summary>
        internal static string TemporaryUptimeManager_DeleteTemporaryUptimeError {
            get {
                return ResourceManager.GetString("TemporaryUptimeManager_DeleteTemporaryUptimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading temporary uptime.
        /// </summary>
        internal static string TemporaryUptimeManager_LoadTemporaryUptimeError {
            get {
                return ResourceManager.GetString("TemporaryUptimeManager_LoadTemporaryUptimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving temporary uptime.
        /// </summary>
        internal static string TemporaryUptimeManager_SaveTemporaryUptimeError {
            get {
                return ResourceManager.GetString("TemporaryUptimeManager_SaveTemporaryUptimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uptime defined until {0}.
        /// </summary>
        internal static string UptimeCheck_UptimeCheckTemporaryUptimeReason {
            get {
                return ResourceManager.GetString("UptimeCheck_UptimeCheckTemporaryUptimeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uptime defined until {0}.
        /// </summary>
        internal static string UptimeManager_TemporaryUptimeUntil {
            get {
                return ResourceManager.GetString("UptimeManager_TemporaryUptimeUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string UptimeScheduler_UptimeSchedulerExpired {
            get {
                return ResourceManager.GetString("UptimeScheduler_UptimeSchedulerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel wake up timer.
        /// </summary>
        internal static string WakeManager_CancelWakeTimerFailed {
            get {
                return ResourceManager.GetString("WakeManager_CancelWakeTimerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set timer for wake up.
        /// </summary>
        internal static string WakeManager_SetWakeTimerFailed {
            get {
                return ResourceManager.GetString("WakeManager_SetWakeTimerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake scheduled at {0}.
        /// </summary>
        internal static string WakeManager_WakeScheduled {
            get {
                return ResourceManager.GetString("WakeManager_WakeScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake timer cancelled.
        /// </summary>
        internal static string WakeManager_WakeTimerCancelled {
            get {
                return ResourceManager.GetString("WakeManager_WakeTimerCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string WakeScheduler_WakeSchedulerExpired {
            get {
                return ResourceManager.GetString("WakeScheduler_WakeSchedulerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***ERROR***.
        /// </summary>
        internal static string WsapmLog_ErrorIndicator {
            get {
                return ResourceManager.GetString("WsapmLog_ErrorIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***WARNING***.
        /// </summary>
        internal static string WsapmLog_WarningIndicator {
            get {
                return ResourceManager.GetString("WsapmLog_WarningIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking CPU load.
        /// </summary>
        internal static string WsapmManager_CheckCpuLoad {
            get {
                return ResourceManager.GetString("WsapmManager_CheckCpuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking logical volume load.
        /// </summary>
        internal static string WsapmManager_CheckHddLoad {
            get {
                return ResourceManager.GetString("WsapmManager_CheckHddLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking memory load.
        /// </summary>
        internal static string WsapmManager_CheckMemoryLoad {
            get {
                return ResourceManager.GetString("WsapmManager_CheckMemoryLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking access to network shares.
        /// </summary>
        internal static string WsapmManager_CheckNetworkFileAccess {
            get {
                return ResourceManager.GetString("WsapmManager_CheckNetworkFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking network load.
        /// </summary>
        internal static string WsapmManager_CheckNetworkLoad {
            get {
                return ResourceManager.GetString("WsapmManager_CheckNetworkLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking network machines.
        /// </summary>
        internal static string WsapmManager_CheckNetworkMachines {
            get {
                return ResourceManager.GetString("WsapmManager_CheckNetworkMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking processes.
        /// </summary>
        internal static string WsapmManager_CheckProcesses {
            get {
                return ResourceManager.GetString("WsapmManager_CheckProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check scheduled uptimes.
        /// </summary>
        internal static string WsapmManager_CheckScheduledUptimes {
            get {
                return ResourceManager.GetString("WsapmManager_CheckScheduledUptimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service continued.
        /// </summary>
        internal static string WsapmManager_Continued {
            get {
                return ResourceManager.GetString("WsapmManager_Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drives.
        /// </summary>
        internal static string WsapmManager_DisplayNameAllDrives {
            get {
                return ResourceManager.GetString("WsapmManager_DisplayNameAllDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All network interfaces (combined).
        /// </summary>
        internal static string WsapmManager_DisplayNameAllNetworkInterfaces {
            get {
                return ResourceManager.GetString("WsapmManager_DisplayNameAllNetworkInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***ERROR***.
        /// </summary>
        internal static string WsapmManager_ErrorLogFileCaption {
            get {
                return ResourceManager.GetString("WsapmManager_ErrorLogFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacktrace:.
        /// </summary>
        internal static string WsapmManager_ErrorLogStacktraceCaption {
            get {
                return ResourceManager.GetString("WsapmManager_ErrorLogStacktraceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute user defined actions after policy check (at least one policy satisfied).
        /// </summary>
        internal static string WsapmManager_ExecuteActionWhenAtLeastOnePolicySatisfied {
            get {
                return ResourceManager.GetString("WsapmManager_ExecuteActionWhenAtLeastOnePolicySatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute user defined actions after policy check (no policy statisfied).
        /// </summary>
        internal static string WsapmManager_ExecuteActionWhenNoPolicySatisfied {
            get {
                return ResourceManager.GetString("WsapmManager_ExecuteActionWhenNoPolicySatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service paused.
        /// </summary>
        internal static string WsapmManager_Paused {
            get {
                return ResourceManager.GetString("WsapmManager_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset network connections.
        /// </summary>
        internal static string WsapmManager_ResetNetworkConnectionsAfterWake {
            get {
                return ResourceManager.GetString("WsapmManager_ResetNetworkConnectionsAfterWake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting the specified windows services after wake.
        /// </summary>
        internal static string WsapmManager_RestartServicesAfterWake {
            get {
                return ResourceManager.GetString("WsapmManager_RestartServicesAfterWake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Resume after suspend.
        /// </summary>
        internal static string WsapmManager_ResumeAutomatic {
            get {
                return ResourceManager.GetString("WsapmManager_ResumeAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings changed, reloading settings.
        /// </summary>
        internal static string WsapmManager_SettingsChanged {
            get {
                return ResourceManager.GetString("WsapmManager_SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started.
        /// </summary>
        internal static string WsapmManager_Started {
            get {
                return ResourceManager.GetString("WsapmManager_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring timer started.
        /// </summary>
        internal static string WsapmManager_StartMonitoringTimer {
            get {
                return ResourceManager.GetString("WsapmManager_StartMonitoringTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the specified programs after wake.
        /// </summary>
        internal static string WsapmManager_StartProgramsAfterEveryWake {
            get {
                return ResourceManager.GetString("WsapmManager_StartProgramsAfterEveryWake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the specified programs after scheduled wake.
        /// </summary>
        internal static string WsapmManager_StartProgramsAfterWake {
            get {
                return ResourceManager.GetString("WsapmManager_StartProgramsAfterWake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring timer stopped.
        /// </summary>
        internal static string WsapmManager_StopMonitoringTimer {
            get {
                return ResourceManager.GetString("WsapmManager_StopMonitoringTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped.
        /// </summary>
        internal static string WsapmManager_Stopped {
            get {
                return ResourceManager.GetString("WsapmManager_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Computer enters standby mode.
        /// </summary>
        internal static string WsapmManager_Suspend {
            get {
                return ResourceManager.GetString("WsapmManager_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary uptime until {0}.
        /// </summary>
        internal static string WsapmManager_TemporaryUptimeDefined {
            get {
                return ResourceManager.GetString("WsapmManager_TemporaryUptimeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No temporary uptime defined (uptime exceeded or canceled).
        /// </summary>
        internal static string WsapmManager_TemporaryUptimeUnDefined {
            get {
                return ResourceManager.GetString("WsapmManager_TemporaryUptimeUnDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend standby for {0} minutes after automatic resume..
        /// </summary>
        internal static string WsapmManager_TimerStartedAfterResumeAutomatic {
            get {
                return ResourceManager.GetString("WsapmManager_TimerStartedAfterResumeAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available ({0}). Click on &apos;Check for updates&apos; to apply the update.
        /// </summary>
        internal static string WsapmManager_UpdateAvailable {
            get {
                return ResourceManager.GetString("WsapmManager_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows idle timeout ({0} minutes) is greater than the set check interval ({1} minutes).
        /// </summary>
        internal static string WsapmManager_ValidationErrorCheckInterval {
            get {
                return ResourceManager.GetString("WsapmManager_ValidationErrorCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &apos;Allow wake timers&apos; is disabled in the Windows power options.
        /// </summary>
        internal static string WsapmManager_ValidationErrorWakeTimers {
            get {
                return ResourceManager.GetString("WsapmManager_ValidationErrorWakeTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake timer elapsed.
        /// </summary>
        internal static string WsapmManager_WakeTimerCompleted {
            get {
                return ResourceManager.GetString("WsapmManager_WakeTimerCompleted", resourceCulture);
            }
        }
    }
}
